# Generated by Django 2.0.5 on 2018-05-23 11:28

import content.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(db_index=True)),
                ('alias', models.TextField(unique=True)),
                ('intro', models.TextField(default='', null=True)),
                ('content', models.TextField(default='', null=True)),
                ('img_url', models.URLField(default='', null=True)),
                ('img_path', models.ImageField(default='', null=True, upload_to='')),
                ('state', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.ForeignKey(on_delete=models.SET(content.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('edited_at', models.ForeignKey(on_delete=models.SET(content.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_at', models.ForeignKey(on_delete=models.SET(content.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
