# Generated by Django 2.0.5 on 2018-05-27 07:49

import content.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180524_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(content.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='edited_at',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(content.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_path',
            field=models.ImageField(default='', null=True, upload_to='article/imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(content.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
