# Generated by Django 2.0.5 on 2018-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180527_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created'], 'permissions': (('can_publish_articles', 'Can publish articles'),), 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='edited',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
