# Generated by Django 2.0.5 on 2018-05-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20180527_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published_at',
        ),
    ]
