# Generated by Django 2.0.5 on 2018-05-30 10:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180529_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
