# Generated by Django 2.0.5 on 2018-05-30 10:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_article_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_html',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
