# Generated by Django 2.0.5 on 2018-05-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180530_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_html',
        ),
    ]
